### ISSUE TITLE
Not able to run

### ISSUE THREAD

**Issue by mobilutz** [henry-spanka/homebridge-buschjaeger#1]
Hi @henry-spanka 

I just stumbled over this repo yesterday and I am really really interested in it.

Unfortunately, I could not get `homebridge` to run:
```
[3/11/2018, 9:34:17 PM] ---
/usr/local/lib/node_modules/homebridge/lib/server.js:212
  var username = config.bridge.username;
```

It seems that maybe you based the README on an older version on homebridge, or am I doing something wrong?

Thanks

**Comment by mobilutz** [comment]
Sorry, my bad.

I didn't see the part `in the platform section` in here: https://github.com/henry-spanka/homebridge-buschjaeger#configuration

**Comment by henry-spanka** [comment]
Great. So did it work for you now?
I will release a new version soon when the necessary changes that I currently depend on are merged.
See: https://github.com/sstadlberger/home/pull/15

Please use the version from NPM right now as the GitHub master version won't work.

**Comment by mobilutz** [comment]
It is running now, I have to add the actuators now.
I found this package through https://github.com/sstadlberger/home and also saw the waiting PR.

**Comment by henry-spanka** [comment]
Great. Then have fun running through your house to find the right accessory that lights up ;)

**Comment by henry-spanka** [comment]
Note that you don't need to add any actuators. The plugin will discover all actuators automatically.

**Comment by mobilutz** [comment]
I mean add the to your code:
`[3/11/2018, 9:47:40 PM] [BuschJaegerSysAp] Ignoring non-supported accessory Sensor/ Jalousieaktor 2/1-fach with serial ABB700D088CF`

**Comment by henry-spanka** [comment]
Great. I believe this is the same as the Jalousieaktor with 4 channels, so you can use the same accessory class. Can you send me the output of: http://API:8080/info/ABB700D088CF?

**Comment by mobilutz** [comment]
That output does not include any sensitive data, right?
I just started with this as we just moved into our house one month ago.

**Comment by henry-spanka** [comment]
No only the state of the accessory. You may want to hide the serial number though, just in case.

**Comment by mobilutz** [comment]
I will send you some more outputs, as all my actors are not yet part of your app.
I'll prepare something and send you a mail to the address from your github account.

**Comment by henry-spanka** [comment]
Sure. You can send me the whole data with: http://API:8080/info. That includes all actuators.

**Comment by mobilutz** [comment]
Done
