### ISSUE TITLE
Some suggestions regarding device names and types

### ISSUE THREAD

**Issue by timboozle** [henry-spanka/homebridge-buschjaeger#13]
Hi, now that I got everything working I'm running into the following issues. 

- First run, everything was okay and the correct amount of devices were visible in Homekit. The only thing was that the device names were pretty incomprehensible. (Like `Sensor/ Schaltaktor 1/1-fach`) and that they were all Outlets instead of Lights.

- I renamed everything and assigned rooms in Homekit. Then I realized I needed to exclude some devices and started using the mapping to blacklist 3 actuators for all channels.

- I restarted Homebridge and now Homekit is a mess. It was a mix of my names and Sensor/ Schaltaktor(...) and there were almost 50 devices instead of the +/-26 I actually have. It seems a lot more unused channels were included.

- Got rid of the mapping and reconnected Homebridge but it's still importing 50 devices. 

So I don't know if this is just me but it would be nice to:
- Import the right amount of devices 
- Get the device names and maybe even room names from the SysAp (Like https://github.com/jheling/freeathome)
- Detect whether it's a light or outlet

Thanks!

**Comment by henry-spanka** [comment]
Hi,
I'm not aware of any issues so it should work just fine.

> First run, everything was okay and the correct amount of devices were visible in Homekit. The only thing was that the device names were pretty incomprehensible. (Like `Sensor/ Schaltaktor 1/1-fach`) and that they were all Outlets instead of Lights.

That is correct. I will take a look at the XML file again to see if there is more information we can get out of it. Currently we only display the device name. A Schaltaktor can be configured as an outlet or light so we can not say for sure if it's a light. However you can go into the settings in HomeKit and change the outlet to a light (or fan).

> I renamed everything and assigned rooms in Homekit. Then I realized I needed to exclude some devices and started using the mapping to blacklist 3 actuators for all channels.

If you exclude some devices then they will be removed from the HomeKit database the next time you start homebridge. Make sure to only exclude the devices you don't need. If you exclude too many devices you need to reconfigure them afterwards.

> I restarted Homebridge and now Homekit is a mess. It was a mix of my names and Sensor/ Schaltaktor(...) and there were almost 50 devices instead of the +/-26 I actually have. It seems a lot more unused channels were included.

HomeKit sometimes needs a few minutes to detect accessory changes. Just open the App multiple times and they should disappear. Alternatively you can remove the bridge (which removes all accessories attached to it) and then repair the bridge.

> Got rid of the mapping and reconnected Homebridge but it's still importing 50 devices.

See my answer above.

To implement the necessary changes we first need to get this into https://github.com/henry-spanka/freeathome-api.

**Comment by timboozle** [comment]
Thanks, did some resetting and everything is working.
