### ISSUE TITLE
Add support for sensor/dimaktor 6212/1.1

### ISSUE THREAD

**Issue by jooste** [henry-spanka/homebridge-buschjaeger#19]
Hi Henry,

Thanks for the great work on the BJ plugin! Apple's home app works so much better than BJ/ABB's app!

In my setup, all of the devices work, except my light dimmer, which is of the type '6262/1.1'. Would it be possible to enable this aktor in your plugin? Since you already have support for the din rail-mounted dimmers hopefully it's just a matter of adding/adapting a few lines of code.

Thanks a lot in advance!
Best,
Joost

**Comment by henry-spanka** [comment]
Hi Joost,

ikr. ABBs app is really falling short when compared to Apple's Home app. And you even need to pay for remote access.

Adding new devices is usually just adding a single line of code. I need the info data structure to be able to add it. Please either post it here or send it to my email address (see GitHub profile). You can usually get the info data with `curl http://localhost:8080/info > info.json`

**Comment by jooste** [comment]
Hi Henry,

Just to be sure, with localhost you mean the machine where homebridge is running?

**Comment by henry-spanka** [comment]
Hi,

yes. You should run the command on the homebridge server(where the free@home API is running).

**Comment by jooste** [comment]
Hi Henry,

Just sent you an email with the json output!

Best,
Joost

**Comment by henry-spanka** [comment]
Thanks.

Added support for the dimmer in commit e4791b6ff1c949a88b76d1804c26f0ff4c74aad0.

Please try to install the master version of the homebridge plugin and let me know if it works.
You can install the master version with: `npm install henry-spanka/homebridge-buschjaeger#master`

I recommend that you only whitelist the channel `ch0003`. Otherwise you will get multiple accessories in HomeKit as the binary sensor is mapped to a dimming actuator (which of course doesn't work).

**Comment by jooste** [comment]
Works like a charm! As for the whitelisting, I indeed get all of the sensors of each sensor/aktor combination as additional listed (non-functioning) device. I currently have a large list of blacklisted devices/channels to remedy that. The channel numbers to blacklist are predictable though: for 1.X devices only channel ch0000, for 2.X devices both channel ch0000 and ch0003.

**Comment by henry-spanka** [comment]
👍 Great! I have already added support for automatically discovering the right channels in the free@home API project but had no time to implement this into homebridge yet. Maybe I will do it at some time but I don't think it's really important as of right now. Takes a little longer to setup everything but other than that no real benefit.

I think we can consider this solved now. Can I close the issue?

**Comment by jooste** [comment]
Indeed, with blacklisting it works fine as it is! I will close the issue, thanks again for the very quick response!
