### ISSUE TITLE
Dimmaktor / Schaltaktor 4-fach

### ISSUE THREAD

**Issue by vschroederdo** [henry-spanka/homebridge-buschjaeger#3]
Hi ,
I have just installed your app and I am thrilled. After that I searched a long time.
Unfortunately, my dimming actuator is not recognized. He has the DeviceID 101C.
It would be great if the switch actuator 4fach still maintained.
I will send you an email with the API info.

Thank you

**Comment by henry-spanka** [comment]
Great, I'm happy to hear that.
Unfortunately your dimming actuator seems to work differently from the actuator I have although it's basically the same.

**Comment by henry-spanka** [comment]
Well it does behave the same, ch0000 was just not assigned.
Added support in commit 4979d4ed9115dd14bb49fd814df7e39879ecbcc4

**Comment by henry-spanka** [comment]
Support for Schaltaktor 4-fach, 16A, REG (B002) was added in commit 0039fddbd45cc6ea1f22cae2e244b7a6a962283e
