### ISSUE TITLE
Add support for Schaltaktor 2/2-fach

### ISSUE THREAD

**Issue by williamvz** [henry-spanka/homebridge-buschjaeger#6]
Hi, 

Love the work so far. However, I have a number of 2/2-sensor / schaltaktor actors. Would it be possible to add support for those as well? 

Thanks in advance! 

William

**Comment by williamvz** [comment]
Hm, this is odd. I believe I posted a description to this issue yesterday too. Never mind. So I’m looking for 2/2-fach Schaltaktor support in this plugin. would be great if it could be realized. I tried looking up the device ID’s but could not find them. Be willing to help if you can direct me there.

**Comment by henry-spanka** [comment]
Hello,
glad you like it. To add support for 2/2-fach Schaltaktor, I need the device ID's. If you send me the json formatted info file, I can get the ID's myself and the corresponding data points needed to communicate with the actuator.

Please run the following command from your local server:
```bash
http://localhost:8080/info > actuators.json
```

Please send me the file `actuators.json` via email (listed in my profile).

**Comment by henry-spanka** [comment]
Hello,
thank you very much. Support has been added in commit 696d0c604ecd28889653cfab250920e6104cc168 and a new version 1.3.0 released.

Please update the npm module with npm update homebridge-buschjaeger.

**Comment by williamvz** [comment]
Hi Henry, 

Looks like I updated the bunch tonight but they are not popping up after restarting the API and Homebridge, nor after re-pairing homebridge to the iPhone. Please check the screenshot attached that shows the location of the index.js file, as well as the content, and the terminal screen, showing that homebridge ignores the 2/2-fach Schaltaktor. Any thoughts? Did I overlook something? The 1/1-fach's are showing up. 
![schermafdruk 2018-06-05 23 11 21](https://user-images.githubusercontent.com/37240069/41003329-c7579e9c-6916-11e8-92c3-5402cab802e9.png)

**Comment by henry-spanka** [comment]
You don't need to repair the bridge. Restarting home bridge should be enough. Are you sure that the updated version is running? You may try to reboot your pi to make sure no old processes are running.
I have double checked and it should definitely not print "not supported".

**Comment by williamvz** [comment]
I wanted to be thorough. :) 

I rebooted the Pi and checked the version: 1.3.0. The readme shows the 2/2-fach's as well. Could it have anything to do with the channels? I do see that it displays the channels after the device ID's for the initialised ones but not for the ignored ones. 

![schermafdruk 2018-06-06 16 25 29](https://user-images.githubusercontent.com/37240069/41044788-4f22d3d8-69a7-11e8-91b9-b63a589883c6.png)

**Comment by henry-spanka** [comment]
That is very weird.
Please try to replace line `90` in `index.js` with:
```javascript
this.log('Ignoring non-supported accessory ' + actuator['typeName'] + ' with serial ' + serial + ' deviceId ' + deviceId);
```

The module can be found in `node_modules/homebridge-buschjaeger`.
Restart home bridge and check the log if it displays the device id now.

**Comment by williamvz** [comment]
Hi Henry, 

Just updated index.js, but not much of an effect. It still ignores them and neither do they appear in the Home app on my iPhone. The log is shown below. Could it be that there are two device ID's or something like that given there are two physical buttons on the switch? 

![bj2fach](https://user-images.githubusercontent.com/37240069/41316956-12cf9d70-6e94-11e8-8b9f-b1a61acce5f8.png)

**Comment by henry-spanka** [comment]
Hello,
it definitely should show a log message if you manually edit the source. Do you have installed the module globally? Please check with `npm list -g | grep homebridge-buschjaeger`. If it produces output then you have installed it globally and you need to update the module with `npm update home bridge-buschjaeger -g`

**Comment by williamvz** [comment]
Whoops! That did the trick, yes. Apologies for overlooking that. It was installed globally and still on 1.2.0. Upgrading it now activated all the 2/2-fach actors. 

Thanks again!

**Comment by henry-spanka** [comment]
Happy to hear that ;)
