### ISSUE TITLE
unable to git clone sstadlberger api

### ISSUE THREAD

**Issue by TheSpirit** [henry-spanka/homebridge-buschjaeger#7]
unable to git clone sstadlberger api.

![bildschirmfoto 2018-06-18 um 19 32 11](https://user-images.githubusercontent.com/6056918/41552261-8fecd43c-732e-11e8-919d-b913368952ac.png)

what am I doing wrong?

**Comment by henry-spanka** [comment]
Hello,
you need to add your public key to your profile at GitHub.
However you can also clone with https without authentication
Try: `git clone https://github.com/sstadlberger/home.git`

**Comment by TheSpirit** [comment]
thanks

i did:
1. install node.js: https://nodejs.org/
2. clone the repository: git clone git@github.com:sstadlberger/home.git
3. cd into the project root and install the node modules: npm install
4. configure the config.js, data.json and structure.json files (see the files themselves and below for more information)
5. run it with: node home.js (possible options: --logLevel=debug --useWeather --useDB --useHomematic)
i have done 1-4. do i have to do point 5 too or is this done within homebridge?

**Comment by henry-spanka** [comment]
These are two separate projects. You need to start the API first (step 5). Any command line options are not required. `node home.js` should be sufficient.

**Comment by TheSpirit** [comment]
Thx. 
Can you tell me how to do a systemd service?
I am on a raspberry pi

**Comment by henry-spanka** [comment]
Sure.
Create a new file `/etc/systemd/system/buschjaeger-api.service` and add the following content:

`
[Unit]
Description=Busch Jaeger API Service
Wants=network-online.target
After=network-online.target

[Service]
Type=simple
ExecStart=/usr/bin/node home.js
Restart=on-failure
User=root
Group=root
WorkingDirectory=/root/buschjaeger/api

[Install]
WantedBy=multi-user.target
`

Change the WorkingDirectory to the path where the API is installed.

Then run `systemctl daemon-reload` and `systemctl enable buschjaeger-api.service`.
You can start/stop it manually with `systemctl start buschjaeger-api.service´ etc.

**Comment by TheSpirit** [comment]
i think it does not autostart on boot.
what could be the problem?
thanks

**Comment by henry-spanka** [comment]
Hi,
try to reboot the server and execute ‘systemctl status buschjaeger-api.service’
 and check if it is running. 

Note that for homebridge you need to create another systemd service.

**Comment by TheSpirit** [comment]
works now just fine.
thanks a lot

**Comment by henry-spanka** [comment]
Great :)
