### ISSUE TITLE
Recently installed no auto discovery

### ISSUE THREAD

**Issue by SRTMG** [henry-spanka/homebridge-buschjaeger#9]
Hello. 

I recently installed a Homebridge system and wanted to integrate my Busch Jäger Free@Home system with the help of the plugin offered here. After I have installed the plugin and have all the data in my HomeBridge Config as specified in the ReadMe, the HomeBridge console tells me that the plugin has loaded successfully, but if I now add the HomeBridge to my Home App on the Iphone it tells me there are no switchable devices.

The Busch-Jaeger API seems to work because I can control an actuator with an http request.

Can you help me with that?

Here still my Homebridge Config:

```
`{`
        "bridge": {
                "name": "Homebridge",
                "username": "CC:22:3D:E3:CE:31",
                "port": 51826,
                "pin": "031-45-155"
        },

        "accessories": [

        ],

        "platfroms": [{
                "platform": "BuschJaegerSysAp",
                "sysIP": "172.16.0.19",
                "updateInterval": 60,
                "mappings": {}
        }]
`}`
```

And here the output of my HomeBridge Console: http://prntscr.com/l938gk

If I look for the BuschJäger API data there is also a result (http://<BuschJaegerAPIIP:8080/info).

Hope you can help me... :/

Greetings

SRTMG

**Comment by SRTMG** [comment]
Yes ~/.homebridge/config.json can this problem occure if the plugin isn't installed right?

**Comment by henry-spanka** [comment]
Uhm,
it should work.
Have you installed the plugin with the `-g` flag? If not try: `npm install homebridge-buschjaeger -g`

**Comment by SRTMG** [comment]
So after testing a while I finally decided to reinstall the whole server. Now everything is working fine :)

**Comment by henry-spanka** [comment]
Glad to hear that you got it working ;)
If you have any actuators that are not supported, feel free to open an issue so I can take a look at it.
